name: CI
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: clean
        run: make deep_clean

      - name: build
        run: sbt compile

      - name: plugin-test
        run: make test_plugin

      - name: unit-test-coverage
        run: make test_coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Save coveralls.json file
#        # https://stackoverflow.com/a/58353477/3357831
#        uses: peter-evans/create-pull-request@v3.12.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: Update coveralls file
#          title: Update coveralls file
#          draft: true
#          add-paths: |
#            ./coveralls
#          branch: coveralls_file

      - name: clean-up
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
