name: Release
on:
  push:
    branches: [ main ]
    tags: [ "*" ]
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PGP_SECRET: ${{ secrets.PGP_SECRET }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: test-coverage
        run: |
          export COVERALLS_REPO_TOKEN="pKjQ0Lr189Gu9HbGez15vXvVSFNgEgZmr" && make test_coverage
        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: github-actions

      - name: release-staging
        run: sbt ";set isSnapshot := true ; clean ; ci-release"
        if: startsWith(github.ref, 'refs/tags/') != true

      - name: release-production
        run: sbt "; clean ; ci-release"
        if: startsWith(github.ref, 'refs/tags/v')

      - name: clean-up
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt  
